import express from 'express';
console.log('express ok');
import cors from 'cors';
console.log('cors ok');
import helmet from 'helmet';
console.log('helmet ok');
import morgan from 'morgan';
console.log('morgan ok');
import dotenv from 'dotenv';
console.log('dotenv ok');
import cookieParser from 'cookie-parser';
console.log('cookie-parser ok');
import mongoose from 'mongoose';
console.log('mongoose ok');
import connectDB from './config/db.js';
console.log('connectDB ok');
import authRoutes from './routes/authRoutes.js';
console.log('authRoutes ok');
import roadmapRoutes from './routes/roadmapRoutes.js';
console.log('roadmapRoutes ok');
